version: "3.8"

services:

  accounts:
    image: microservice/accounts:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - microservice-network

  loans:
    image: microservice/loans:latest
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - microservice-network

  cards:
    image: microservice/cards:latest
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - microservice-network

networks:
  microservice-network: